export const themes = {
  boards: [
    { name: 'green', displayName: 'Green', creator: 'chess.com' },
    { name: 'dark_wood', displayName: 'Dark Wood', creator: 'chess.com' },
    { name: 'glass', displayName: 'Glass', creator: 'chess.com' },
    { name: 'brown', displayName: 'Brown', creator: 'chess.com' },
    { name: 'icy_sea', displayName: 'Icy Sea', creator: 'chess.com' },
    { name: 'newspaper', displayName: 'Newspaper', creator: 'chess.com' },
    { name: 'walnut', displayName: 'Walnut', creator: 'chess.com' },
    { name: 'sky', displayName: 'Sky', creator: 'chess.com' },
    { name: 'lolz', displayName: 'Lolz', creator: 'chess.com' },
    { name: 'stone', displayName: 'Stone', creator: 'chess.com' },
    { name: 'bases', displayName: 'Bases', creator: 'chess.com' },
    { name: '8_bit', displayName: '8-Bit', creator: 'chess.com' },
    { name: 'marble@lichess.org', displayName: 'Marble', creator: 'chess.com' },
    { name: 'purple', displayName: 'Purple', creator: 'chess.com' },
    { name: 'translucent', displayName: 'Translucent', creator: 'chess.com' },
    { name: 'metal@lichess.org', displayName: 'Metal', creator: 'chess.com' },
    { name: 'tournament', displayName: 'Tournament', creator: 'chess.com' },
    { name: 'dash', displayName: 'Dash', creator: 'chess.com' },
    { name: 'burled_wood', displayName: 'Burled Wood', creator: 'chess.com' },
    { name: 'blue', displayName: 'Blue', creator: 'chess.com' },
    { name: 'bubblegum', displayName: 'Bubblegum', creator: 'chess.com' },
    { name: 'checkers', displayName: 'Checkers', creator: 'chess.com' },
    { name: 'graffiti', displayName: 'Graffiti', creator: 'chess.com' },
    { name: 'light', displayName: 'Light', creator: 'chess.com' },
    { name: 'neon', displayName: 'Neon', creator: 'chess.com' },
    { name: 'orange', displayName: 'Orange', creator: 'chess.com' },
    { name: 'overlay', displayName: 'Overlay', creator: 'chess.com' },
    { name: 'parchment', displayName: 'Parchment', creator: 'chess.com' },
    { name: 'red', displayName: 'Red', creator: 'chess.com' },
    { name: 'sand', displayName: 'Sand', creator: 'chess.com' },
    { name: 'tan', displayName: 'Tan', creator: 'chess.com' },
    { name: 'blue-marble', displayName: 'Blue Marble', creator: 'lichess.org' },
    { name: 'blue2', displayName: 'Blue2', creator: 'lichess.org' },
    { name: 'blue3', displayName: 'Blue3', creator: 'lichess.org' },
    { name: 'canvas2', displayName: 'Canvas2', creator: 'lichess.org' },
    {
      name: 'green-plastic',
      displayName: 'Green Plastic',
      creator: 'lichess.org',
    },
    { name: 'grey', displayName: 'Grey', creator: 'lichess.org' },
    { name: 'horsey', displayName: 'Horsey', creator: 'lichess.org' },
    { name: 'leather', displayName: 'Leather', creator: 'lichess.org' },
    { name: 'maple', displayName: 'Maple', creator: 'lichess.org' },
    { name: 'maple2', displayName: 'Maple2', creator: 'lichess.org' },
    { name: 'marble', displayName: 'Marble', creator: 'lichess.org' },
    { name: 'metal', displayName: 'Metal', creator: 'lichess.org' },
    { name: 'nfc-board', displayName: 'NFC Board', creator: 'lichess.org' },
    { name: 'olive', displayName: 'Olive', creator: 'lichess.org' },
    {
      name: 'pink-pyramid',
      displayName: 'Pink Pyramid',
      creator: 'lichess.org',
    },
    { name: 'purple-diag', displayName: 'Purple Diag', creator: 'lichess.org' },
    { name: 'wood', displayName: 'Wood', creator: 'lichess.org' },
    { name: 'wood2', displayName: 'Wood2', creator: 'lichess.org' },
    { name: 'wood3', displayName: 'Wood3', creator: 'lichess.org' },
    { name: 'wood4', displayName: 'Wood4', creator: 'lichess.org' },
  ],
  pieces: [
    { name: 'neo', displayName: 'Neo', creator: 'chess.com' },
    { name: 'game_room', displayName: 'Game Room', creator: 'chess.com' },
    { name: 'wood', displayName: 'Wood', creator: 'chess.com' },
    { name: 'glass', displayName: 'Glass', creator: 'chess.com' },
    { name: 'gothic', displayName: 'Gothic', creator: 'chess.com' },
    { name: 'classic', displayName: 'Classic', creator: 'chess.com' },
    { name: 'metal', displayName: 'Metal', creator: 'chess.com' },
    { name: 'bases', displayName: 'Bases', creator: 'chess.com' },
    { name: 'neo_wood', displayName: 'Neo-Wood', creator: 'chess.com' },
    { name: 'icy_sea', displayName: 'Icy Sea', creator: 'chess.com' },
    { name: 'club', displayName: 'Club', creator: 'chess.com' },
    { name: 'ocean', displayName: 'Ocean', creator: 'chess.com' },
    { name: 'newspaper', displayName: 'Newspaper', creator: 'chess.com' },
    { name: 'blindfold', displayName: 'Blindfold', creator: 'chess.com' },
    { name: 'space', displayName: 'Space', creator: 'chess.com' },
    { name: 'cases', displayName: 'Cases', creator: 'chess.com' },
    { name: 'condal', displayName: 'Condal', creator: 'chess.com' },
    { name: '3d_chesskid', displayName: '3D - ChessKid', creator: 'chess.com' },
    { name: '8_bit', displayName: '8-Bit', creator: 'chess.com' },
    { name: 'marble', displayName: 'Marble', creator: 'chess.com' },
    { name: 'book', displayName: 'Book', creator: 'chess.com' },
    { name: 'alpha', displayName: 'Alpha', creator: 'chess.com' },
    { name: 'bubblegum', displayName: 'Bubblegum', creator: 'chess.com' },
    { name: 'dash', displayName: 'Dash', creator: 'chess.com' },
    { name: 'graffiti', displayName: 'Graffiti', creator: 'chess.com' },
    { name: 'light', displayName: 'Light', creator: 'chess.com' },
    { name: 'lolz', displayName: 'Lolz', creator: 'chess.com' },
    { name: 'luca', displayName: 'Luca', creator: 'chess.com' },
    { name: 'maya', displayName: 'Maya', creator: 'chess.com' },
    { name: 'modern', displayName: 'Modern', creator: 'chess.com' },
    { name: 'nature', displayName: 'Nature', creator: 'chess.com' },
    { name: 'neon', displayName: 'Neon', creator: 'chess.com' },
    { name: 'sky', displayName: 'Sky', creator: 'chess.com' },
    { name: 'tigers', displayName: 'Tigers', creator: 'chess.com' },
    { name: 'tournament', displayName: 'Tournament', creator: 'chess.com' },
    { name: 'vintage', displayName: 'Vintage', creator: 'chess.com' },
    { name: '3d_wood', displayName: '3D - Wood', creator: 'chess.com' },
    { name: '3d_staunton', displayName: '3D - Staunton', creator: 'chess.com' },
    { name: '3d_plastic', displayName: '3D - Plastic', creator: 'chess.com' },
    { name: 'kosal', displayName: 'Kosal', creator: 'lichess.org' },
    { name: 'riohacha', displayName: 'Riohacha', creator: 'lichess.org' },
    { name: 'governor', displayName: 'Governor', creator: 'lichess.org' },
    { name: 'horsey', displayName: 'Horsey', creator: 'lichess.org' },
    { name: 'cardinal', displayName: 'Cardinal', creator: 'lichess.org' },
    { name: 'kiwen-suwi', displayName: 'Kiwen-Suwi', creator: 'lichess.org' },
    { name: 'maestro', displayName: 'Maestro', creator: 'lichess.org' },
    { name: 'fresca', displayName: 'Fresca', creator: 'lichess.org' },
    { name: 'gioco', displayName: 'Gioco', creator: 'lichess.org' },
    { name: 'caliente', displayName: 'Caliente', creator: 'lichess.org' },
    { name: 'icpieces', displayName: 'Icpieces', creator: 'lichess.org' },
    { name: 'letter', displayName: 'Letter', creator: 'lichess.org' },
    { name: 'shapes', displayName: 'Shapes', creator: 'lichess.org' },
    { name: 'reillycraig', displayName: 'Reillycraig', creator: 'lichess.org' },
    { name: 'anarcandy', displayName: 'Anarcandy', creator: 'lichess.org' },
    { name: 'staunty', displayName: 'Staunty', creator: 'lichess.org' },
    { name: 'dubrovny', displayName: 'Dubrovny', creator: 'lichess.org' },
    { name: 'tatiana', displayName: 'Tatiana', creator: 'lichess.org' },
    { name: 'pixel', displayName: 'Pixel', creator: 'lichess.org' },
    { name: 'merida', displayName: 'Merida', creator: 'lichess.org' },
    { name: 'mpchess', displayName: 'Mpchess', creator: 'lichess.org' },
    { name: 'chessnut', displayName: 'Chessnut', creator: 'lichess.org' },
    { name: 'celtic', displayName: 'Celtic', creator: 'lichess.org' },
    { name: 'leipzig', displayName: 'Leipzig', creator: 'lichess.org' },
    { name: 'mono', displayName: 'Mono', creator: 'lichess.org' },
    { name: 'libra', displayName: 'Libra', creator: 'lichess.org' },
    { name: 'chess7', displayName: 'Chess7', creator: 'lichess.org' },
    { name: 'pirouetti', displayName: 'Pirouetti', creator: 'lichess.org' },
    { name: 'spatial', displayName: 'Spatial', creator: 'lichess.org' },
    { name: 'california', displayName: 'California', creator: 'lichess.org' },
    { name: 'fantasy', displayName: 'Fantasy', creator: 'lichess.org' },
    { name: 'cburnett', displayName: 'Cburnett', creator: 'lichess.org' },
    { name: 'companion', displayName: 'Companion', creator: 'lichess.org' },
  ],
};
